declare module 'galaxia/fileSystem' {
  export * from '../../lib/functions/fileSystem.js'
  export {
    dirExists,
    dirExistsSync,
    emptyDir,
    emptyDirSync,
    ensureDir,
    ensureDirSync,
    ensureFile,
    ensureFileSync,
    fileExists,
    fileExistsSync,
    dirMtimeDeep,
    dirMtimeDeepSync,
    dirStats,
    dirStatsSync,
    fileSize,
    fileSizeSync,
    fileStats,
    fileStatsSync,
    isDir,
    isDirSync,
    isFile,
    isFileSync,
    isDirEmpty,
    isDirEmptySync,
    readDir,
    readDirSync,
    readFile,
    readFileSync,
    readJson,
    readJsonSync,
    readJson5,
    readJson5Sync,
    remove,
    deleteDir,
    deleteFile,
    removeSync,
    deleteDirSync,
    deleteFileSync,
    writeJson,
    writeJsonSync,
    writeJson5,
    writeJson5Sync,
    writeFile,
    writeFileSync
    // @ts-ignore Prevents an error when types are generated
  } from '../../lib/functions/fileSystem.js'
}
